package com.entities;
// Generated 8 avr. 2018 00:43:56 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReservationId generated by hbm2java
 */
@Embeddable
public class ReservationId implements java.io.Serializable {

	private int id;
	private int halfDayId;

	public ReservationId() {
	}

	public ReservationId(int id, int halfDayId) {
		this.id = id;
		this.halfDayId = halfDayId;
	}

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "half_day_id", nullable = false)
	public int getHalfDayId() {
		return this.halfDayId;
	}

	public void setHalfDayId(int halfDayId) {
		this.halfDayId = halfDayId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservationId))
			return false;
		ReservationId castOther = (ReservationId) other;

		return (this.getId() == castOther.getId()) && (this.getHalfDayId() == castOther.getHalfDayId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getHalfDayId();
		return result;
	}

}
