package com.entities;
// Generated 8 avr. 2018 00:43:56 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HalfDay generated by hbm2java
 */
@Entity
@Table(name = "half_day", catalog = "nursery_webapp")
public class HalfDay implements java.io.Serializable {

	private Integer id;
	private Date date;
	private String period;
	private Byte offDay;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public HalfDay() {
	}

	public HalfDay(Date date, String period) {
		this.date = date;
		this.period = period;
	}

	public HalfDay(Date date, String period, Byte offDay, Set<Reservation> reservations) {
		this.date = date;
		this.period = period;
		this.offDay = offDay;
		this.reservations = reservations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "period", nullable = false, length = 45)
	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	@Column(name = "off_day")
	public Byte getOffDay() {
		return this.offDay;
	}

	public void setOffDay(Byte offDay) {
		this.offDay = offDay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "halfDay")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
