package com.entities;
// Generated 8 avr. 2018 00:43:56 by Hibernate Tools 5.2.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "nursery_webapp", uniqueConstraints = @UniqueConstraint(columnNames = "id"))
public class Reservation implements java.io.Serializable {

	private int id;
	private Boolean absent;
	private Boolean justification;
	
	private Contract contract;
	private HalfDay halfDay;

	public Reservation() {
	}

	public Reservation(int id, HalfDay halfDay, Contract contract) {
		this.id = id;
		this.halfDay = halfDay;
		this.contract = contract;
	}

	public Reservation(int id, HalfDay halfDay, Boolean absent, Boolean justification, Contract contract) {
		this.id = id;
		this.halfDay = halfDay;
		this.absent = absent;
		this.justification = justification;
		this.contract = contract;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", unique = true, nullable = false)),
			@AttributeOverride(name = "halfDayId", column = @Column(name = "half_day_id", nullable = false)),
			@AttributeOverride(name = "contractId", column = @Column(name = "contract_id", nullable = false)) })
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "half_day_id", nullable = false, insertable = false, updatable = false)
	public HalfDay getHalfDay() {
		return this.halfDay;
	}

	public void setHalfDay(HalfDay halfDay) {
		this.halfDay = halfDay;
	}

	@Column(name = "absent")
	public Boolean getAbsent() {
		return this.absent;
	}

	public void setAbsent(Boolean absent) {
		this.absent = absent;
	}

	@Column(name = "justification")
	public Boolean getJustification() {
		return this.justification;
	}

	public void setJustification(Boolean justification) {
		this.justification = justification;
	}
	
	@OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "contract_id")
	public Contract getContract() {
		return this.contract;
	}

	public void setContract(Contract contract) {
		this.contract = contract;
	}

}
